#!/usr/bin/env sh

if [ $# == 0 ]
then
    echo "usage: $0 module_address (on|off)"
    exit 1
fi

res=`curl -sX PUT -d "value=$2" 192.168.1.19/api/modules/$1`
if [ "$res" != "OK" ]
then
    echo $res
fi
