#!/usr/bin/env sh

SERVER_HOSTNAME="192.168.1.216"
SERVER_PORT="80"

if [ $# -eq 0 ]
then
    echo "usage: $0 module_address {on|off}"
    exit 1
fi

curl -s http://$DORMCTL_SERVER/api/modules/$1?value=$2 > /dev/null
